### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by appsforartists** [material-motion-archive/coreanimation-swift#1]
Shouldn't it be `material-motion-core-animation-family-swift`?  That's the name you've used in the [podspec](https://github.com/material-motion/material-motion-family-coreanimation-swift/blob/develop/MaterialMotionCoreAnimationFamily.podspec) and the one that's easiest to read.

(Unless you are trying to lexographically group them, e.g. `material-motion/family/core-animation`).

**Comment by jverkoey** [comment]
Is for the latter reason.
