### ISSUE TITLE
Exploration: UIView block-based animations

### ISSUE THREAD

**Issue by jverkoey** [material-motion-archive/coreanimation-swift#14]
Many people are used to UIView's implicit animation APIs.

Material Motion, on the other hand, is much closer to Core Animation's API patterns.

This task tracks explorations for supporting UIView implicit APIs, or something similar in Material Motion.

This is a research task and may not lead to any spec'able outcome.

**Comment by jverkoey** [comment]
https://www.objc.io/issues/12-animations/view-layer-synergy/

**Comment by jverkoey** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1904

**Comment by jverkoey** [comment]
💻 I'm working on a diff at http://codereview.cc/D1904

**Comment by jverkoey** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1904

**Comment by chuga** [comment]
nit: this should be renamed to "Exploration: UIView block-based animations"
